### ISSUE TITLE
When evaluating the pushT task, it keeps prompting: reset env!!!

### ISSUE THREAD

**Issue by jmwang0117** [jeffacce/dynamo_ssl#5]
Thank you for your excellent work. 

I encountered the following problem when evaluating the push-T task. 

How can I solve it? Thank you!

![image](https://github.com/user-attachments/assets/3cf1ddaf-edf0-49b4-8cda-c3e7ef8788e0)

**Comment by jeffacce** [comment]
You can comment out this line: https://github.com/jeffacce/dynamo_ssl/blob/3e9282759d4e94ae828879281f2e47fcc4171892/envs/pusht.py#L1052
