### ISSUE TITLE
Performance on learning-from-scratch

### ISSUE THREAD

**Issue by lingxiao-guo** [jeffacce/dynamo_ssl#7]
Hi,Jeff,very impressive work! But I'm curious that if you've compared any learning-from-scratch(Lfs) methods in your paper, since Lfs has been revealed sometimes stronger performance than Pretrained representations[1]. Also, I notice the  performance of diffusion policy with DynaMo on push-T is 0.73, where in the original DP paper, the performance of DP-C is 0.91/0.84 and DP-T is 0.78/0.66. It seems that DynaMo isn't very competent compared to the original DP. Could you explain why and how DynaMo compares to Lfs baseline? Thanks a lot!

[1].Hansen N, Yuan Z, Ze Y, et al. On pre-training for visuo-motor control: Revisiting a learning-from-scratch baseline[J]. arXiv preprint arXiv:2212.05749, 2022.

**Comment by jeffacce** [comment]
Hi Lingxiao,

Thanks for your interest in our work! Yes we've run that before, and end-to-end learning from a randomly initialized ResNet18 did 0.21 on Push-T. To experiment with learning-from-scratch baselines on your own machine, you can modify `online_eval.py` and replace the embedding dataset with a vision backbone encoding the images during training.

We use the DP-T implementation with frozen embeddings, without augmentations or fine-tuning, which is a different setup from the diffusion policy paper.

The diffusion policy paper evaluates the visual Push-T environment with end-to-end fine-tuning and data augmentation, whereas we freeze the encoders and run policy training across different frozen representations to make sure that the downstream policy training does not confound our evaluation. The main point of our paper is to compare different visual representations, agnostic to downstream policy architectures. We use the image inputs as is without augmentation during policy eval.

Let me know if you have any other questions.

Best,
Jeff

**Comment by lingxiao-guo** [comment]
Thanks very much! Would love to give it a try.
